"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.mcTokenToolbox = exports.lst = exports.wrapError = exports.assets = exports.Auth = exports.Social = void 0;
const tslib_1 = require("tslib");
const auth_js_1 = tslib_1.__importDefault(require("./auth/auth.js"));
exports.Auth = auth_js_1.default;
const assets = tslib_1.__importStar(require("./assets.js"));
exports.assets = assets;
const assets_js_1 = require("./assets.js");
Object.defineProperty(exports, "wrapError", { enumerable: true, get: function () { return assets_js_1.wrapError; } });
Object.defineProperty(exports, "lst", { enumerable: true, get: function () { return assets_js_1.lst; } });
const social_1 = tslib_1.__importDefault(require("./auth/social.js"));
exports.Social = social_1.default;
const minecraft_js_1 = require("./auth/minecraft.js");
exports.mcTokenToolbox = { fromToken: minecraft_js_1.fromToken, fromMclcToken: minecraft_js_1.fromMclcToken, validate: minecraft_js_1.validate };
